### ISSUE TITLE
Error while setting up hasl3 platform for binary_sensor

### ISSUE THREAD

**Issue by captnswing** [hasl-sensor/integration#35]
Using Home Assistant Core to version 2022.3.2
slapi-v3.0.4

Error while setting up hasl3 platform for binary_sensor

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/hasl3/binary_sensor.py", line 34, in async_setup_entry
    async_add_devices(await setup_hasl_sensor(hass, config_entry))
  File "/config/custom_components/hasl3/binary_sensor.py", line 44, in setup_hasl_sensor
    if not config.options[CONF_ANALOG_SENSORS]:
KeyError: 'analog'
```

**Comment by DSorlov** [comment]
Could you try remove and then re-adding the sensor?
