### ISSUE TITLE
Departure sensor error

### ISSUE THREAD

**Issue by DSorlov** [hasl-sensor/integration#6]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 355, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 409, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/hasl3/sensor.py", line 458, in device_state_attributes
    val['attribution'] = self._sensordata["attribution"]
KeyError: 'attribution'

**Comment by DSorlov** [comment]
Resolved in [3.0.0-beta.2](https://github.com/hasl-sensor/integration/releases/tag/3.0.0-beta.2)
